#!/bin/bash
readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/include/cmd.bash"
source "$DIR/include/fn.bash"
source "$DIR/include/utils.bash"
source "$DIR/include/commands/env.bash"
source "$DIR/include/commands/service.bash"
source "$DIR/include/commands/build.bash"
source "$DIR/include/commands/dyno.bash"
source "$DIR/include/commands/pg.bash"

if [[ "$BASH_VERSINFO" -lt "4" ]]; then
	echo "!! Your system Bash is out of date: $BASH_VERSION"
	echo "!! Please upgrade to Bash 4 or greater."
	exit 2
fi

readonly identifier="devoku"
readonly port="${DEVOKU_PORT:-8000}"

if [ -f "$PWD/.env.template" ]; then
  readonly env_template_file="$PWD/.env.template"
else
	readonly env_template_file="$DIR/.env.template"
fi

readonly local_share_dir="${DEVOKU_SHARE_DIR:-$PWD}"
readonly local_prefix="${DEVOKU_LOCAL_PREFIX:-$PWD/.$identifier}"
readonly container_prefix="/$identifier"

readonly local_app_dir="$local_prefix/app"
readonly local_cache_dir="$local_prefix/cache"
readonly local_slug_file="$local_prefix/slug.tar.gz"
readonly local_env_file="$local_prefix/.env"
readonly container_slug_file="$container_prefix/slug.tar.gz"
readonly container_env_file="$container_prefix/.env"
readonly container_share_dir="$container_prefix/share"

readonly herokuish_image="${DEVOKU_HEROKUISH_IMAGE:-gliderlabs/herokuish:latest}"
readonly postgres_image="${DEVOKU_POSTGRES_IMAGE:-postgres:9.5}"
readonly redis_image="${DEVOKU_POSTGRES_IMAGE:-redis:latest}"
readonly fake_s3_image="${ODOOKU_POSTGRES_IMAGE:-lphoward/fake-s3:latest}"

check-docker() {
	docker info > /dev/null 2>&1 || {
		echo >&2 "Docker is not installed";
		exit 100;
	}
}

check-git() {
	git version > /dev/null 2>&1 || {
		echo >&2 "Git is not installed";
		exit 110;
	}

	git rev-parse HEAD > /dev/null 2>&1 || {
		echo >&2 "$PWD is not a valid git repository";
		exit 111;
	}
}

ensure-dirs() {
  mkdir -p $local_prefix $local_app_dir $local_cache_dir
}

remove-dirs() {
	rm -rf $local_app_dir $local_cache_dir
}

paths() {
	title "Devoku paths"
	echo "env template file: $env_template_file" |indent
	echo "app repository: $local_app_dir" | indent
	echo "build cache: $local_cache_dir" | indent
	echo "env file: $local_env_file" | indent
}

main() {
	set -eo pipefail; [[ "$TRACE" ]] && set -x

	cmd-export paths
	cmd-export build
	cmd-export clean

	cmd-export-ns env "Manage Herokuish environment"
	cmd-export env-new
	cmd-export env-set
	cmd-export env-print

	cmd-export-ns dyno "Run Herokuish container"
	cmd-export dyno-web
	cmd-export dyno-worker
	cmd-export dyno-run
	cmd-export dyno-shell

	cmd-export-ns pg "Manage PostgreSQL"
	cmd-export pg-psql
	cmd-export pg-createdb
	cmd-export pg-dropdb

	cmd-export-ns service
	cmd-export-ns service-postgres
	cmd-export-ns service-redis
	cmd-export-ns service-s3
	cmd-export service-postgres-up
	cmd-export service-postgres-down
	cmd-export service-redis-up
	cmd-export service-redis-down
	cmd-export service-s3-up
	cmd-export service-s3-down


	case "$1" in
		run)		dyno-run "${@:2}";;
		shell)		dyno-shell "${@:2}";;
		web)		dyno-web "${@:2}";;
		worker)		dyno-worker "${@:2}";;
		*)			cmd-ns "" "$@";
	esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	main "$@"
fi
