site_name: Devoku
site_description: Herokuish development environment for just about any project
site_author: Raymond Reggers
site_url: http://adaptivdesign.github.io/devoku/

theme: material

# Copyright
copyright: Copyright (c) 2016 Raymond Reggers

extra:
  version: '0.1.0'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'deep purple'
    accent: 'light purple'

# Extensions
markdown_extensions:
  - codehilite:
  - admonition:
  - toc:
      permalink: '#'

# Page tree
pages:
  - Devoku: index.md
  - Getting started: getting-started.md
  - Commands: commands.md
  - Custom Environment: custom-environment.md
